type PlatformType = 'normal' | 'moving' | 'break' | 'spring';
type Platform = { x:number; y:number; w:number; h:number; type:PlatformType; vx:number; broken:boolean };
type Bonus = { x:number; y:number; kind:'star'|'shield'|'jetpack'; taken:boolean };
type Enemy = { x:number; y:number; vx:number; phase:number; active:boolean };

const W=480,H=680,BEST_KEY='nowis:doodle-jump:best';

export function upgradeDoodleJump(doc:Document,win:Window){
  const root=doc.documentElement;if(!root||root.dataset.nowisDoodlePro==='true')return;root.dataset.nowisDoodlePro='true';root.lang='fr';doc.title='Doodle Jump NOWIS';doc.head.querySelectorAll('link[rel="stylesheet"],script[src]').forEach(n=>n.remove());
  const style=doc.createElement('style');style.textContent=`
    :root{color-scheme:dark;font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif}*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:#07111f;color:#fff}body{min-height:100dvh;overflow:hidden;user-select:none;-webkit-tap-highlight-color:transparent}button{font:inherit}
    .app{min-height:100dvh;display:flex;flex-direction:column;align-items:center;gap:7px;padding:max(7px,env(safe-area-inset-top)) max(7px,env(safe-area-inset-right)) max(9px,env(safe-area-inset-bottom)) max(7px,env(safe-area-inset-left));background:radial-gradient(circle at 50% 0%,rgba(56,189,248,.17),transparent 30%),linear-gradient(#0f2940,#07111f)}
    .head,.hud,.game-wrap,.tools,.controls{width:min(100%,560px)}.head{display:flex;align-items:center;justify-content:space-between}.brand small{display:block;color:#7dd3fc;font-size:10px;font-weight:900;letter-spacing:.16em;text-transform:uppercase}.brand h1{margin:2px 0 0;font-size:clamp(21px,6vw,31px);letter-spacing:-.04em}.head button,.tools button,.controls button,.card button{min-height:42px;border:1px solid rgba(148,163,184,.24);border-radius:12px;background:#0f172a;color:#e2e8f0;font-weight:850;cursor:pointer}.head button{min-width:42px}
    .hud{display:grid;grid-template-columns:repeat(5,1fr);gap:5px}.stat{padding:6px 3px;text-align:center;border:1px solid rgba(56,189,248,.18);border-radius:10px;background:rgba(15,23,42,.76)}.stat span{display:block;font-size:9px;color:#94a3b8;font-weight:900;text-transform:uppercase;letter-spacing:.07em}.stat strong{display:block;margin-top:2px;font-size:clamp(13px,3.8vw,18px);font-variant-numeric:tabular-nums}
    .game-wrap{position:relative;min-height:0;flex:1;display:flex;justify-content:center;overflow:hidden;border:1px solid rgba(56,189,248,.25);border-radius:19px;background:#bde7ff;padding:5px;box-shadow:0 22px 60px rgba(0,0,0,.45)}#doodleCanvas{height:100%;max-height:calc(100dvh - 210px);width:auto;max-width:100%;aspect-ratio:480/680;background:#c9efff;border-radius:14px;touch-action:none}.message{position:absolute;top:12%;left:50%;transform:translateX(-50%);padding:7px 12px;border-radius:999px;background:rgba(15,23,42,.86);border:1px solid rgba(255,255,255,.16);color:#fef08a;font-size:12px;font-weight:1000;opacity:0;transition:.18s;pointer-events:none;white-space:nowrap}.message.show{opacity:1}
    .tools{display:grid;grid-template-columns:repeat(4,1fr);gap:5px}.tools button{padding:6px 3px;font-size:11px}.tools .primary{border-color:rgba(56,189,248,.38);background:rgba(14,116,144,.22);color:#cffafe}.controls{display:grid;grid-template-columns:1fr 1fr;gap:8px}.controls button{min-height:56px;font-size:26px;touch-action:none;background:linear-gradient(#1e293b,#0f172a)}.controls button.active{background:#164e63;border-color:#22d3ee;transform:scale(.97)}
    .overlay{position:fixed;inset:0;z-index:50;display:flex;align-items:center;justify-content:center;padding:18px;background:rgba(2,6,23,.84);backdrop-filter:blur(12px)}.overlay.hidden{display:none}.card{width:min(100%,430px);border:1px solid rgba(56,189,248,.28);border-radius:20px;background:linear-gradient(155deg,#0f172a,#172554);padding:22px;box-shadow:0 30px 80px rgba(0,0,0,.58)}.card small{color:#7dd3fc;font-weight:900;text-transform:uppercase;letter-spacing:.16em}.card h2{margin:5px 0 8px;font-size:28px;letter-spacing:-.04em}.card p{color:#cbd5e1;line-height:1.5}.legend{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin:14px 0}.legend div{padding:8px;border-radius:11px;background:rgba(30,41,59,.75);font-size:11px;color:#e2e8f0}.actions{display:grid;grid-template-columns:1fr 1fr;gap:7px}.card button{padding:11px}.card .primary{background:#0369a1;border-color:#38bdf8;color:#fff}
    @media(min-width:700px){.controls{max-width:300px}.game-wrap{flex:0 1 auto}#doodleCanvas{height:min(70dvh,680px)}}
  `;doc.head.appendChild(style);
  doc.body.innerHTML=`
    <main class="app"><header class="head"><div class="brand"><small>Arcade NOWIS</small><h1>Doodle Jump</h1></div><button id="soundBtn">🔊</button></header>
    <section class="hud"><div class="stat"><span>Hauteur</span><strong id="score">0</strong></div><div class="stat"><span>Record</span><strong id="best">0</strong></div><div class="stat"><span>Combo</span><strong id="combo">×1</strong></div><div class="stat"><span>Bouclier</span><strong id="shield">—</strong></div><div class="stat"><span>Bonus</span><strong id="bonus">0</strong></div></section>
    <section class="game-wrap"><canvas id="doodleCanvas" width="480" height="680"></canvas><div class="message" id="message">SUPER SAUT !</div></section>
    <section class="tools"><button class="primary" id="pauseBtn">⏸ Pause</button><button id="restartBtn">↻ Rejouer</button><button id="difficultyBtn">⚡ Normal</button><button id="helpBtn">? Aide</button></section>
    <section class="controls"><button data-move="left">←</button><button data-move="right">→</button></section></main>
    <div class="overlay" id="intro"><section class="card"><small>Nouvelle version NOWIS</small><h2>Monte le plus haut possible</h2><p>Les plateformes deviennent plus variées avec l’altitude : mobiles, cassantes et ressorts. Ramasse des étoiles, un bouclier ou un jetpack et évite les monstres.</p><div class="legend"><div>🟢 Plateforme normale</div><div>🔵 Plateforme mobile</div><div>🟠 Cassante</div><div>🟣 Ressort</div><div>⭐ +250 points</div><div>🛡 Protection</div></div><div class="actions"><button class="primary" id="startBtn">Jouer</button><button id="fastBtn">Mode rapide</button></div></section></div>
    <div class="overlay hidden" id="pauseOverlay"><section class="card"><small>Pause</small><h2>Souffle un peu</h2><p>Ta montée est conservée.</p><div class="actions"><button class="primary" id="resumeBtn">Reprendre</button><button id="pauseRestart">Recommencer</button></div></section></div>
    <div class="overlay hidden" id="result"><section class="card"><small id="resultSmall">Partie terminée</small><h2 id="resultTitle">Belle montée !</h2><p id="resultText"></p><div class="actions"><button class="primary" id="againBtn">Rejouer</button><button id="closeResult">Voir le score</button></div></section></div>
    <div class="overlay hidden" id="help"><section class="card"><small>Comment jouer</small><h2>Le saut est automatique</h2><p>Déplace-toi avec gauche/droite. Tu rebondis dès que tu atterris sur une plateforme. Plus tu montes, plus la génération devient exigeante. Le jetpack te propulse sans avoir besoin de plateforme.</p><div class="actions"><button class="primary" id="closeHelp">Compris</button><button id="helpPlay">Jouer</button></div></section></div>
  `;
  const canvas=doc.getElementById('doodleCanvas') as HTMLCanvasElement,ctx=canvas.getContext('2d');if(!ctx)return;const scoreEl=doc.getElementById('score')!,bestEl=doc.getElementById('best')!,comboEl=doc.getElementById('combo')!,shieldEl=doc.getElementById('shield')!,bonusEl=doc.getElementById('bonus')!,message=doc.getElementById('message')!,intro=doc.getElementById('intro')!,pauseOverlay=doc.getElementById('pauseOverlay')!,result=doc.getElementById('result')!,resultSmall=doc.getElementById('resultSmall')!,resultTitle=doc.getElementById('resultTitle')!,resultText=doc.getElementById('resultText')!,help=doc.getElementById('help')!,soundBtn=doc.getElementById('soundBtn') as HTMLButtonElement,difficultyBtn=doc.getElementById('difficultyBtn') as HTMLButtonElement;
  let platforms:Platform[]=[],bonuses:Bonus[]=[],enemies:Enemy[]=[];let player={x:222,y:560,vx:0,vy:0,w:36,h:42};let camera=0,highest=0,score=0,best=Number(win.localStorage.getItem(BEST_KEY)||0),combo=1,stars=0,shield=0,jetpack=0,running=false,paused=false,last=0,difficulty=1,soundOn=true,left=false,right=false,platformHits=0;
  type AudioWin=Window&typeof globalThis&{webkitAudioContext?:typeof AudioContext};const AC=(win as AudioWin).AudioContext||(win as AudioWin).webkitAudioContext;let audio:AudioContext|null=null;function tone(f:number,d=.05,v=.025){if(!soundOn||!AC)return;try{audio??=new AC();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.setValueAtTime(v,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d);}catch{}}
  function say(text:string,ms=700){message.textContent=text;message.classList.add('show');win.setTimeout(()=>message.classList.remove('show'),ms)}
  function rand(min:number,max:number){return min+Math.random()*(max-min)}
  function platformType(alt:number):PlatformType{const r=Math.random(),hard=Math.min(.38,alt/9000);if(r<.08+hard*.2)return'spring';if(r<.19+hard*.4)return'break';if(r<.35+hard)return'moving';return'normal'}
  function addPlatform(y:number,first=false){const alt=Math.max(0,-y);const gap=rand(55,92+Math.min(28,alt/180));const w=first?110:rand(Math.max(54,105-alt/260),118);const type=first?'normal':platformType(alt);platforms.push({x:first?(W-w)/2:rand(5,W-w-5),y,w,h:13,type,vx:type==='moving'?(Math.random()<.5?-1:1)*rand(.6,1.3):0,broken:false});if(!first&&Math.random()<.105){const kind:Bonus['kind']=Math.random()<.62?'star':Math.random()<.7?'shield':'jetpack';bonuses.push({x:platforms.at(-1)!.x+w/2-9,y:y-25,kind,taken:false});}if(!first&&alt>1200&&Math.random()<Math.min(.16,.04+alt/22000))enemies.push({x:rand(30,W-60),y:y-rand(35,80),vx:(Math.random()<.5?-1:1)*rand(.45,1),phase:Math.random()*Math.PI*2,active:true});return y-gap;}
  function init(){platforms=[];bonuses=[];enemies=[];let y=H-70;y=addPlatform(y,true);while(y>-H)y=addPlatform(y);player={x:222,y:H-120,vx:0,vy:-11.2,w:36,h:42};camera=0;highest=player.y;score=0;combo=1;stars=0;shield=0;jetpack=0;left=false;right=false;platformHits=0;last=0;running=true;paused=false;intro.classList.add('hidden');pauseOverlay.classList.add('hidden');result.classList.add('hidden');updateHud();say('GO !',500)}
  function ensurePlatforms(){let top=platforms.length?Math.min(...platforms.map(p=>p.y)):camera;while(top>camera-H-240)top=addPlatform(top);platforms=platforms.filter(p=>p.y-camera<H+130&&!p.broken);bonuses=bonuses.filter(b=>b.y-camera<H+130&&!b.taken);enemies=enemies.filter(e=>e.y-camera<H+130&&e.active)}
  function updateHud(){scoreEl.textContent=Math.floor(score).toLocaleString('fr-CA');bestEl.textContent=Math.floor(best).toLocaleString('fr-CA');comboEl.textContent=`×${combo}`;shieldEl.textContent=shield>0?'🛡':'—';bonusEl.textContent=String(stars)}
  function collect(){for(const b of bonuses){if(b.taken)continue;if(player.x+player.w>b.x&&player.x<b.x+22&&player.y+player.h>b.y&&player.y<b.y+22){b.taken=true;if(b.kind==='star'){stars++;score+=250*combo;tone(880,.08);say('+250 ⭐',500)}else if(b.kind==='shield'){shield=1;tone(660,.1);say('BOUCLIER !',650)}else{jetpack=1.7;tone(1050,.12);say('JETPACK !',700)}try{win.navigator.vibrate?.(18)}catch{}}}}
  function hitEnemy(){for(const e of enemies){if(!e.active)continue;if(player.x+player.w>e.x&&player.x<e.x+34&&player.y+player.h>e.y&&player.y<e.y+34){if(shield){shield=0;e.active=false;score+=300;tone(740,.08);say('BOUCLIER SAUVE !',650)}else endGame();return}}}
  function physics(dt:number){const factor=Math.min(2.2,dt*60);if(left)player.vx=Math.max(-5.4*difficulty,player.vx-.72*factor);else if(right)player.vx=Math.min(5.4*difficulty,player.vx+.72*factor);else player.vx*=Math.pow(.78,factor);player.x+=player.vx*factor;if(player.x<-player.w/2)player.x=W-player.w/2;if(player.x>W-player.w/2)player.x=-player.w/2;
    if(jetpack>0){jetpack-=dt;player.vy=-9.8*difficulty;}else player.vy+=.43*factor;const prevBottom=player.y+player.h;player.y+=player.vy*factor;
    if(player.vy>0){for(const p of platforms){if(p.broken)continue;const nowBottom=player.y+player.h;if(prevBottom<=p.y+4&&nowBottom>=p.y&&player.x+player.w>p.x+4&&player.x<p.x+p.w-4){player.y=p.y-player.h;player.vy=p.type==='spring'?-16.2:-11.3;platformHits++;combo=Math.min(9,1+Math.floor(platformHits/6));if(p.type==='break')p.broken=true;if(p.type==='spring'){score+=120*combo;tone(980,.08);say('SUPER SAUT !',520)}else tone(420+combo*30,.035,.015);break}}}
    highest=Math.min(highest,player.y);const desired=player.y-H*.43;if(desired<camera)camera+=(desired-camera)*Math.min(1,.13*factor);score=Math.max(score,(-highest)*.45+stars*250);if(score>best){best=score;win.localStorage.setItem(BEST_KEY,String(Math.floor(best)))}collect();hitEnemy();ensurePlatforms();if(player.y-camera>H+90)endGame();}
  function drawBackground(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#7dd3fc');g.addColorStop(1,'#e0f2fe');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<16;i++){const y=((i*89-camera*.12)%760+760)%760-40;ctx.fillStyle='rgba(255,255,255,.42)';ctx.beginPath();ctx.ellipse((i*73)%W,y,30+(i%3)*12,9+(i%2)*4,0,0,Math.PI*2);ctx.fill()}}
  function drawPlatform(p:Platform){const y=p.y-camera;if(y<-40||y>H+30)return;const colors:Record<PlatformType,string>={normal:'#22c55e',moving:'#3b82f6',break:'#f59e0b',spring:'#a855f7'};ctx.fillStyle=colors[p.type];ctx.beginPath();ctx.roundRect(p.x,y,p.w,p.h,6);ctx.fill();ctx.fillStyle='rgba(255,255,255,.34)';ctx.fillRect(p.x+7,y+2,Math.max(8,p.w*.35),3);if(p.type==='spring'){ctx.strokeStyle='#f5d0fe';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(p.x+p.w/2-10,y);ctx.lineTo(p.x+p.w/2-5,y-10);ctx.lineTo(p.x+p.w/2,y);ctx.lineTo(p.x+p.w/2+5,y-10);ctx.lineTo(p.x+p.w/2+10,y);ctx.stroke()}}
  function drawPlayer(){const x=player.x,y=player.y-camera;ctx.save();ctx.translate(x+player.w/2,y+player.h/2);if(player.vx<-.2)ctx.scale(-1,1);ctx.translate(-player.w/2,-player.h/2);ctx.fillStyle=jetpack>0?'#f97316':'#1f2937';ctx.beginPath();ctx.roundRect(0,2,player.w,player.h-4,9);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(11,15,6,0,Math.PI*2);ctx.arc(25,15,6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#0f172a';ctx.beginPath();ctx.arc(13,15,2.8,0,Math.PI*2);ctx.arc(27,15,2.8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#22c55e';ctx.fillRect(6,player.h-4,10,5);ctx.fillRect(22,player.h-4,10,5);if(shield){ctx.strokeStyle='rgba(34,211,238,.75)';ctx.lineWidth=3;ctx.beginPath();ctx.arc(player.w/2,player.h/2,28+Math.sin(performance.now()/100)*2,0,Math.PI*2);ctx.stroke()}if(jetpack>0){ctx.fillStyle='#fde047';ctx.beginPath();ctx.moveTo(7,player.h);ctx.lineTo(14,player.h+18);ctx.lineTo(20,player.h);ctx.fill()}ctx.restore()}
  function drawBonus(b:Bonus){if(b.taken)return;const y=b.y-camera;if(y<-30||y>H+30)return;ctx.font='22px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(b.kind==='star'?'⭐':b.kind==='shield'?'🛡️':'🚀',b.x+11,y+11)}
  function drawEnemy(e:Enemy,t:number){if(!e.active)return;const y=e.y-camera+Math.sin(t/220+e.phase)*7;if(y<-40||y>H+40)return;e.x+=e.vx;if(e.x<10||e.x>W-44)e.vx*=-1;ctx.fillStyle='#ef4444';ctx.beginPath();ctx.arc(e.x+17,y+17,16,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(e.x+12,y+13,4,0,Math.PI*2);ctx.arc(e.x+23,y+13,4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#111827';ctx.fillRect(e.x+10,y+26,14,3)}
  function frame(t:number){const dt=Math.min(.035,last?(t-last)/1000:0);last=t;if(running&&!paused)physics(dt);drawBackground();platforms.forEach(drawPlatform);bonuses.forEach(drawBonus);enemies.forEach(e=>drawEnemy(e,t));drawPlayer();updateHud();win.requestAnimationFrame(frame)}
  function endGame(){if(!running)return;running=false;tone(160,.3,.04);try{win.navigator.vibrate?.([35,45,35])}catch{}resultSmall.textContent=score>=best&&score>0?'Nouveau record':'Partie terminée';resultTitle.textContent=score>=best&&score>0?'Record battu !':'Belle montée !';resultText.textContent=`Hauteur : ${Math.floor(score).toLocaleString('fr-CA')} · Étoiles : ${stars} · Record : ${Math.floor(best).toLocaleString('fr-CA')}`;result.classList.remove('hidden')}
  function togglePause(){if(!running)return;paused=!paused;pauseOverlay.classList.toggle('hidden',!paused);last=0}
  doc.getElementById('startBtn')?.addEventListener('click',()=>{difficulty=1;difficultyBtn.textContent='⚡ Normal';init()});doc.getElementById('fastBtn')?.addEventListener('click',()=>{difficulty=1.12;difficultyBtn.textContent='🔥 Rapide';init()});doc.getElementById('pauseBtn')?.addEventListener('click',togglePause);doc.getElementById('resumeBtn')?.addEventListener('click',togglePause);doc.getElementById('restartBtn')?.addEventListener('click',init);doc.getElementById('pauseRestart')?.addEventListener('click',init);doc.getElementById('againBtn')?.addEventListener('click',init);doc.getElementById('closeResult')?.addEventListener('click',()=>result.classList.add('hidden'));doc.getElementById('helpBtn')?.addEventListener('click',()=>{paused=true;help.classList.remove('hidden')});doc.getElementById('closeHelp')?.addEventListener('click',()=>{help.classList.add('hidden');paused=false;last=0});doc.getElementById('helpPlay')?.addEventListener('click',()=>{help.classList.add('hidden');if(!running)init();else{paused=false;last=0}});difficultyBtn.addEventListener('click',()=>{difficulty=difficulty>1?1:1.12;difficultyBtn.textContent=difficulty>1?'🔥 Rapide':'⚡ Normal';say(difficulty>1?'MODE RAPIDE':'MODE NORMAL',500)});soundBtn.addEventListener('click',()=>{soundOn=!soundOn;soundBtn.textContent=soundOn?'🔊':'🔇';if(soundOn)tone(520,.06)});
  const key=(down:boolean,e:KeyboardEvent)=>{if(e.key==='ArrowLeft'||e.key==='a'||e.key==='A'){left=down;e.preventDefault()}if(e.key==='ArrowRight'||e.key==='d'||e.key==='D'){right=down;e.preventDefault()}if(down&&(e.key==='p'||e.key==='P'))togglePause()};doc.addEventListener('keydown',e=>key(true,e));doc.addEventListener('keyup',e=>key(false,e));doc.querySelectorAll<HTMLButtonElement>('[data-move]').forEach(btn=>{const isLeft=btn.dataset.move==='left';const set=(v:boolean)=>{if(isLeft)left=v;else right=v;btn.classList.toggle('active',v)};btn.addEventListener('pointerdown',e=>{e.preventDefault();set(true)});btn.addEventListener('pointerup',()=>set(false));btn.addEventListener('pointercancel',()=>set(false));btn.addEventListener('pointerleave',()=>set(false))});
  bestEl.textContent=Math.floor(best).toLocaleString('fr-CA');init();running=false;intro.classList.remove('hidden');win.requestAnimationFrame(frame);
}
