type Pipe = { x:number; gapY:number; gap:number; passed:boolean; perfect:boolean; speed:number };
type Particle = { x:number; y:number; vx:number; vy:number; life:number; size:number };

const W=420,H=680,BEST_KEY='nowis:flappy-bird:best',MEDAL_KEY='nowis:flappy-bird:medal';

export function upgradeFlappyBird(doc:Document,win:Window){
  const root=doc.documentElement;
  if(!root||root.dataset.nowisFlappyPro==='true')return;
  root.dataset.nowisFlappyPro='true';root.lang='fr';doc.title='Flappy Bird NOWIS';
  doc.head.querySelectorAll('link[rel="stylesheet"],script[src]').forEach(n=>n.remove());

  const style=doc.createElement('style');style.textContent=`
    :root{color-scheme:dark;font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif}*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:#071426;color:#fff}body{min-height:100dvh;overflow:hidden;user-select:none;-webkit-tap-highlight-color:transparent}button{font:inherit}
    .app{min-height:100dvh;display:flex;flex-direction:column;align-items:center;gap:7px;padding:max(7px,env(safe-area-inset-top)) max(7px,env(safe-area-inset-right)) max(9px,env(safe-area-inset-bottom)) max(7px,env(safe-area-inset-left));background:radial-gradient(circle at 50% -10%,rgba(56,189,248,.22),transparent 32%),linear-gradient(#0c1f38,#071426)}
    .head,.hud,.game-wrap,.tools{width:min(100%,520px)}.head{display:flex;align-items:center;justify-content:space-between;gap:8px}.brand small{display:block;color:#7dd3fc;font-size:10px;font-weight:900;letter-spacing:.16em;text-transform:uppercase}.brand h1{margin:2px 0 0;font-size:clamp(22px,6vw,31px);letter-spacing:-.04em}.head button,.tools button,.card button{min-height:42px;border:1px solid rgba(148,163,184,.25);border-radius:12px;background:#0f172a;color:#e2e8f0;font-weight:850;cursor:pointer}.head button{min-width:42px}
    .hud{display:grid;grid-template-columns:repeat(5,1fr);gap:5px}.stat{padding:6px 3px;text-align:center;border:1px solid rgba(56,189,248,.2);border-radius:10px;background:rgba(15,23,42,.78)}.stat span{display:block;font-size:9px;color:#94a3b8;font-weight:900;text-transform:uppercase;letter-spacing:.07em}.stat strong{display:block;margin-top:2px;font-size:clamp(13px,3.7vw,18px);font-variant-numeric:tabular-nums}
    .game-wrap{position:relative;min-height:0;flex:1;display:flex;justify-content:center;overflow:hidden;border:1px solid rgba(56,189,248,.28);border-radius:20px;background:#7dd3fc;padding:5px;box-shadow:0 24px 70px rgba(0,0,0,.48)}#flappyCanvas{height:100%;max-height:calc(100dvh - 170px);width:auto;max-width:100%;aspect-ratio:420/680;border-radius:15px;touch-action:manipulation;background:#7dd3fc}.message{position:absolute;top:15%;left:50%;transform:translateX(-50%);padding:7px 12px;border-radius:999px;background:rgba(2,6,23,.84);border:1px solid rgba(255,255,255,.18);font-size:12px;font-weight:1000;color:#fef08a;opacity:0;transition:.18s;pointer-events:none;white-space:nowrap}.message.show{opacity:1}
    .tools{display:grid;grid-template-columns:repeat(4,1fr);gap:5px}.tools button{padding:6px 3px;font-size:11px}.tools .primary{border-color:rgba(56,189,248,.42);background:rgba(14,116,144,.24);color:#cffafe}
    .overlay{position:fixed;inset:0;z-index:50;display:flex;align-items:center;justify-content:center;padding:18px;background:rgba(2,6,23,.86);backdrop-filter:blur(12px)}.overlay.hidden{display:none}.card{width:min(100%,430px);border:1px solid rgba(56,189,248,.3);border-radius:20px;background:linear-gradient(155deg,#0f172a,#172554);padding:22px;box-shadow:0 30px 80px rgba(0,0,0,.58)}.card small{color:#7dd3fc;font-weight:900;text-transform:uppercase;letter-spacing:.16em}.card h2{margin:5px 0 8px;font-size:28px;letter-spacing:-.04em}.card p{color:#cbd5e1;line-height:1.5}.legend{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin:14px 0}.legend div{padding:8px;border-radius:11px;background:rgba(30,41,59,.78);font-size:11px;color:#e2e8f0}.actions{display:grid;grid-template-columns:1fr 1fr;gap:7px}.card button{padding:11px}.card .primary{background:#0369a1;border-color:#38bdf8;color:#fff}
    @media(min-width:700px){.game-wrap{flex:0 1 auto}#flappyCanvas{height:min(76dvh,680px)}}
  `;doc.head.appendChild(style);

  doc.body.innerHTML=`
    <main class="app"><header class="head"><div class="brand"><small>Arcade NOWIS</small><h1>Flappy Bird</h1></div><button id="soundBtn" aria-label="Son">🔊</button></header>
    <section class="hud"><div class="stat"><span>Score</span><strong id="score">0</strong></div><div class="stat"><span>Record</span><strong id="best">0</strong></div><div class="stat"><span>Série</span><strong id="combo">×1</strong></div><div class="stat"><span>Niveau</span><strong id="level">1</strong></div><div class="stat"><span>Médaille</span><strong id="medal">—</strong></div></section>
    <section class="game-wrap"><canvas id="flappyCanvas" width="420" height="680" aria-label="Jeu Flappy Bird"></canvas><div class="message" id="message">PARFAIT !</div></section>
    <section class="tools"><button class="primary" id="pauseBtn">⏸ Pause</button><button id="restartBtn">↻ Rejouer</button><button id="difficultyBtn">⚡ Normal</button><button id="helpBtn">? Aide</button></section></main>
    <div class="overlay" id="intro"><section class="card"><small>Nouvelle version NOWIS</small><h2>Vole entre les tuyaux</h2><p>Tape l’écran ou appuie sur espace pour battre des ailes. Passe au centre des ouvertures pour créer une série parfaite et multiplier les points.</p><div class="legend"><div>🟢 Passage = +1</div><div>✨ Centre parfait = bonus</div><div>🥉 10 points</div><div>🥈 25 points</div><div>🥇 50 points</div><div>💎 100 points</div></div><div class="actions"><button class="primary" id="startBtn">Jouer</button><button id="fastBtn">Mode rapide</button></div></section></div>
    <div class="overlay hidden" id="pauseOverlay"><section class="card"><small>Pause</small><h2>Partie en pause</h2><p>Ton score et ta série sont conservés.</p><div class="actions"><button class="primary" id="resumeBtn">Reprendre</button><button id="pauseRestart">Recommencer</button></div></section></div>
    <div class="overlay hidden" id="result"><section class="card"><small id="resultSmall">Partie terminée</small><h2 id="resultTitle">Bien joué !</h2><p id="resultText"></p><div class="actions"><button class="primary" id="againBtn">Rejouer</button><button id="closeResult">Voir le parcours</button></div></section></div>
    <div class="overlay hidden" id="help"><section class="card"><small>Comment jouer</small><h2>Un bouton, beaucoup de précision</h2><p>Tape n’importe où dans le jeu, clique ou appuie sur Espace/↑. Plus ton score monte, plus les tuyaux accélèrent et l’ouverture rétrécit légèrement. Les passages au centre augmentent ta série et donnent des points bonus.</p><div class="actions"><button class="primary" id="closeHelp">Compris</button><button id="helpPlay">Jouer</button></div></section></div>
  `;

  const canvas=doc.getElementById('flappyCanvas') as HTMLCanvasElement;
  const context=canvas.getContext('2d');if(!context)return;const ctx=context;
  const scoreEl=doc.getElementById('score')!,bestEl=doc.getElementById('best')!,comboEl=doc.getElementById('combo')!,levelEl=doc.getElementById('level')!,medalEl=doc.getElementById('medal')!,message=doc.getElementById('message')!,intro=doc.getElementById('intro')!,pauseOverlay=doc.getElementById('pauseOverlay')!,result=doc.getElementById('result')!,help=doc.getElementById('help')!,resultSmall=doc.getElementById('resultSmall')!,resultTitle=doc.getElementById('resultTitle')!,resultText=doc.getElementById('resultText')!,soundBtn=doc.getElementById('soundBtn') as HTMLButtonElement,difficultyBtn=doc.getElementById('difficultyBtn') as HTMLButtonElement;
  let bird={x:112,y:H*.48,vy:0,r:16,rot:0};let pipes:Pipe[]=[],particles:Particle[]=[];let score=0,best=Number(win.localStorage.getItem(BEST_KEY)||0),combo=1,perfectStreak=0,level=1,running=false,paused=false,last=0,spawn=0,soundOn=true,difficulty=1,groundX=0,flash=0;
  type AudioWin=Window&typeof globalThis&{webkitAudioContext?:typeof AudioContext};const AC=(win as AudioWin).AudioContext||(win as AudioWin).webkitAudioContext;let audio:AudioContext|null=null;
  function tone(f:number,d=.05,v=.025){if(!soundOn||!AC)return;try{audio??=new AC();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.setValueAtTime(v,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
  function say(text:string,ms=650){message.textContent=text;message.classList.add('show');win.setTimeout(()=>message.classList.remove('show'),ms)}
  function medalFor(n:number){return n>=100?'💎':n>=50?'🥇':n>=25?'🥈':n>=10?'🥉':'—'}
  function updateHud(){scoreEl.textContent=String(score);bestEl.textContent=String(best);comboEl.textContent=`×${combo}`;levelEl.textContent=String(level);medalEl.textContent=medalFor(score)}
  function spawnPipe(){const gap=Math.max(126,184-level*5-(difficulty-1)*18);const min=95+gap/2,max=H-125-gap/2;const gapY=min+Math.random()*(max-min);pipes.push({x:W+40,gapY,gap,passed:false,perfect:false,speed:(2.65+level*.11)*difficulty})}
  function reset(){bird={x:112,y:H*.48,vy:0,r:16,rot:0};pipes=[];particles=[];score=0;combo=1;perfectStreak=0;level=1;spawn=.4;groundX=0;flash=0;running=true;paused=false;last=0;intro.classList.add('hidden');pauseOverlay.classList.add('hidden');result.classList.add('hidden');updateHud();say('GO !',450)}
  function flap(){if(!running||paused)return;bird.vy=-7.35*difficulty**.1;bird.rot=-.35;tone(620,.04,.018);for(let i=0;i<4;i++)particles.push({x:bird.x-12,y:bird.y+5,vx:-1-Math.random()*1.5,vy:(Math.random()-.5)*1.6,life:1,size:2+Math.random()*3});try{win.navigator.vibrate?.(8)}catch{}}
  function perfectBurst(){for(let i=0;i<16;i++){const a=Math.random()*Math.PI*2,s=1+Math.random()*3;particles.push({x:bird.x,y:bird.y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:1,size:2+Math.random()*4})}flash=.16}
  function collision(p:Pipe){const left=p.x,right=p.x+74,topGap=p.gapY-p.gap/2,bottomGap=p.gapY+p.gap/2;const bx=bird.x,by=bird.y,r=bird.r;if(bx+r>left&&bx-r<right&&(by-r<topGap||by+r>bottomGap))return true;return false}
  function endGame(){if(!running)return;running=false;tone(120,.32,.05);try{win.navigator.vibrate?.([60,40,90])}catch{}if(score>best){best=score;win.localStorage.setItem(BEST_KEY,String(best));resultSmall.textContent='Nouveau record !'}else resultSmall.textContent='Partie terminée';const medal=medalFor(score);if(medal!=='—')win.localStorage.setItem(MEDAL_KEY,medal);resultTitle.textContent=score>=best&&score>0?'Nouveau sommet !':'Encore un vol ?';resultText.textContent=`Score ${score} · niveau ${level} · meilleure série ×${combo}. Médaille : ${medal}.`;result.classList.remove('hidden');updateHud()}
  function update(dt:number){level=1+Math.floor(score/8);spawn-=dt;if(spawn<=0){spawn=Math.max(.93,1.42-level*.025)/difficulty;spawnPipe()}const factor=dt*60;bird.vy+=.42*factor;bird.y+=bird.vy*factor;bird.rot=Math.min(1.18,bird.rot+.045*factor);groundX=(groundX+2.4*factor)%48;for(const p of pipes){p.x-=p.speed*factor;if(!p.passed&&p.x+74<bird.x){p.passed=true;const dist=Math.abs(bird.y-p.gapY);const perfect=dist<Math.max(14,p.gap*.13);if(perfect){perfectStreak++;combo=Math.min(5,1+Math.floor(perfectStreak/2));score+=combo;p.perfect=true;perfectBurst();tone(880+combo*70,.07,.025);say(combo>1?`PARFAIT ×${combo} !`:'PARFAIT !',550)}else{score+=1;perfectStreak=0;combo=1;tone(520,.04,.018)}if(score>best){best=score;win.localStorage.setItem(BEST_KEY,String(best))}updateHud()}if(collision(p)){endGame();return}}pipes=pipes.filter(p=>p.x>-100);if(bird.y-bird.r<0||bird.y+bird.r>H-64){endGame();return}for(const pt of particles){pt.x+=pt.vx*factor;pt.y+=pt.vy*factor;pt.vy+=.035*factor;pt.life-=dt*1.8}particles=particles.filter(p=>p.life>0);flash=Math.max(0,flash-dt)}
  function drawSky(){const phase=(score%40)/40;const g=ctx.createLinearGradient(0,0,0,H);if(score<20){g.addColorStop(0,'#38bdf8');g.addColorStop(1,'#dbeafe')}else if(score<40){g.addColorStop(0,'#6366f1');g.addColorStop(1,'#fda4af')}else{g.addColorStop(0,'#0f172a');g.addColorStop(1,'#1e3a8a')}ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.globalAlpha=.18;for(let i=0;i<8;i++){const x=(i*97-groundX*.45)%520-50,y=80+(i%4)*72;ctx.fillStyle='#fff';ctx.beginPath();ctx.ellipse(x,y,35+(i%3)*9,11+(i%2)*4,0,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;if(score>=40){for(let i=0;i<28;i++){ctx.fillStyle=`rgba(255,255,255,${.35+(i%3)*.18})`;ctx.fillRect((i*53)%W,(i*83)%420,2,2)}}void phase}
  function drawPipe(p:Pipe){const x=p.x,w=74,top=p.gapY-p.gap/2,bottom=p.gapY+p.gap/2;const grad=ctx.createLinearGradient(x,0,x+w,0);grad.addColorStop(0,'#15803d');grad.addColorStop(.48,'#4ade80');grad.addColorStop(1,'#166534');ctx.fillStyle=grad;ctx.fillRect(x,0,w,top);ctx.fillRect(x,bottom,w,H-bottom-64);ctx.fillStyle='#22c55e';ctx.fillRect(x-5,top-24,w+10,24);ctx.fillRect(x-5,bottom,w+10,24);ctx.fillStyle='rgba(255,255,255,.28)';ctx.fillRect(x+9,0,8,Math.max(0,top-4));ctx.fillRect(x+9,bottom+4,8,H-bottom-68);if(p.perfect){ctx.fillStyle='rgba(250,204,21,.75)';ctx.beginPath();ctx.arc(x+w/2,p.gapY,5,0,Math.PI*2);ctx.fill()}}
  function drawBird(){ctx.save();ctx.translate(bird.x,bird.y);ctx.rotate(bird.rot);ctx.fillStyle='#facc15';ctx.beginPath();ctx.ellipse(0,0,20,15,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fde68a';ctx.beginPath();ctx.ellipse(-7,5,11,7,-.35,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fb923c';ctx.beginPath();ctx.moveTo(17,-1);ctx.lineTo(31,4);ctx.lineTo(17,8);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(7,-6,6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#0f172a';ctx.beginPath();ctx.arc(9,-6,2.4,0,Math.PI*2);ctx.fill();ctx.restore()}
  function draw(){drawSky();pipes.forEach(drawPipe);for(const p of particles){ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle='#fef08a';ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;drawBird();ctx.fillStyle='#84cc16';ctx.fillRect(0,H-64,W,18);ctx.fillStyle='#a16207';ctx.fillRect(0,H-46,W,46);ctx.fillStyle='rgba(255,255,255,.18)';for(let x=-48;x<W+48;x+=48)ctx.fillRect(x-groundX,H-59,24,5);if(flash>0){ctx.fillStyle=`rgba(255,255,255,${flash})`;ctx.fillRect(0,0,W,H)}}
  function loop(ts:number){const dt=Math.min(.033,last?(ts-last)/1000:.016);last=ts;if(running&&!paused)update(dt);draw();win.requestAnimationFrame(loop)}
  function setPause(v:boolean){if(!running)return;paused=v;pauseOverlay.classList.toggle('hidden',!v);if(!v)last=0}
  canvas.addEventListener('pointerdown',e=>{e.preventDefault();flap()});
  doc.addEventListener('keydown',e=>{if([' ','ArrowUp','w','W'].includes(e.key)){e.preventDefault();flap()}if(e.key==='p'||e.key==='P')setPause(!paused)});
  doc.getElementById('startBtn')!.addEventListener('click',()=>{difficulty=1;difficultyBtn.textContent='⚡ Normal';reset()});doc.getElementById('fastBtn')!.addEventListener('click',()=>{difficulty=1.16;difficultyBtn.textContent='🔥 Rapide';reset()});doc.getElementById('pauseBtn')!.addEventListener('click',()=>setPause(true));doc.getElementById('resumeBtn')!.addEventListener('click',()=>setPause(false));doc.getElementById('restartBtn')!.addEventListener('click',reset);doc.getElementById('pauseRestart')!.addEventListener('click',reset);doc.getElementById('againBtn')!.addEventListener('click',reset);doc.getElementById('closeResult')!.addEventListener('click',()=>result.classList.add('hidden'));doc.getElementById('helpBtn')!.addEventListener('click',()=>help.classList.remove('hidden'));doc.getElementById('closeHelp')!.addEventListener('click',()=>help.classList.add('hidden'));doc.getElementById('helpPlay')!.addEventListener('click',()=>{help.classList.add('hidden');if(!running)reset()});difficultyBtn.addEventListener('click',()=>{difficulty=difficulty===1?1.16:1;difficultyBtn.textContent=difficulty===1?'⚡ Normal':'🔥 Rapide';say(difficulty===1?'MODE NORMAL':'MODE RAPIDE',500)});soundBtn.addEventListener('click',()=>{soundOn=!soundOn;soundBtn.textContent=soundOn?'🔊':'🔇'});
  bestEl.textContent=String(best);medalEl.textContent=win.localStorage.getItem(MEDAL_KEY)||'—';updateHud();win.requestAnimationFrame(loop);
}
