type Suit = '♠' | '♥' | '♦' | '♣';
type Card = { id:string; suit:Suit; rank:number; faceUp:boolean };
type Difficulty = 'detente' | 'classique' | 'expert';
type Source = { type:'tableau'; col:number; index:number } | { type:'waste' } | { type:'foundation'; suit:Suit };
type Destination = { type:'tableau'; col:number } | { type:'foundation'; suit:Suit };
type GameState = { tableau:Card[][]; stock:Card[]; waste:Card[]; foundations:Record<Suit,Card[]>; score:number; moves:number; recycles:number };

type Snapshot = { state:GameState; elapsed:number };

const SUITS:Suit[]=['♠','♥','♦','♣'];
const BEST_KEY='nowis:solitaire:stats';
const rankLabel=(r:number)=>r===1?'A':r===11?'J':r===12?'Q':r===13?'K':String(r);
const isRed=(s:Suit)=>s==='♥'||s==='♦';

function cloneCard(c:Card):Card{return{...c}}
function cloneState(s:GameState):GameState{return{tableau:s.tableau.map(col=>col.map(cloneCard)),stock:s.stock.map(cloneCard),waste:s.waste.map(cloneCard),foundations:{'♠':s.foundations['♠'].map(cloneCard),'♥':s.foundations['♥'].map(cloneCard),'♦':s.foundations['♦'].map(cloneCard),'♣':s.foundations['♣'].map(cloneCard)},score:s.score,moves:s.moves,recycles:s.recycles}}
function shuffledDeck():Card[]{const deck:Card[]=[];for(const suit of SUITS)for(let rank=1;rank<=13;rank++)deck.push({id:`${suit}-${rank}`,suit,rank,faceUp:false});for(let i=deck.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]]}return deck}
function deal():GameState{const deck=shuffledDeck(),tableau:Array.from({length:7},()=>[] as Card[]);for(let col=0;col<7;col++)for(let row=0;row<=col;row++){const card=deck.pop()!;card.faceUp=row===col;tableau[col].push(card)}return{tableau,stock:deck,waste:[],foundations:{'♠':[],'♥':[],'♦':[],'♣':[]},score:0,moves:0,recycles:0}}
function movableSequence(cards:Card[]){if(!cards.length||cards.some(c=>!c.faceUp))return false;for(let i=1;i<cards.length;i++)if(isRed(cards[i-1].suit)===isRed(cards[i].suit)||cards[i-1].rank!==cards[i].rank+1)return false;return true}
function canTableau(card:Card,col:Card[]){if(!col.length)return card.rank===13;const top=col[col.length-1];return top.faceUp&&isRed(card.suit)!==isRed(top.suit)&&top.rank===card.rank+1}
function canFoundation(card:Card,pile:Card[]){if(!pile.length)return card.rank===1;const top=pile[pile.length-1];return top.suit===card.suit&&top.rank+1===card.rank}

export function upgradeSolitaire(doc:Document,win:Window){
  const root=doc.documentElement;if(!root||root.dataset.nowisSolitairePro==='true')return;root.dataset.nowisSolitairePro='true';root.lang='fr';doc.title='Solitaire NOWIS';doc.head.querySelectorAll('link[rel="stylesheet"],script[src]').forEach(n=>n.remove());
  const style=doc.createElement('style');style.textContent=`
    :root{color-scheme:dark;font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif;--felt:#075f46;--felt2:#064e3b;--line:rgba(255,255,255,.18)}*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:#032f28;color:#fff}body{min-height:100dvh;overflow-x:hidden;user-select:none;-webkit-tap-highlight-color:transparent}button{font:inherit}
    .sol-app{min-height:100dvh;display:flex;flex-direction:column;align-items:center;gap:7px;padding:max(7px,env(safe-area-inset-top)) max(6px,env(safe-area-inset-right)) max(10px,env(safe-area-inset-bottom)) max(6px,env(safe-area-inset-left));background:radial-gradient(circle at 50% 0%,rgba(52,211,153,.16),transparent 28%),linear-gradient(145deg,var(--felt),var(--felt2))}
    .head,.hud,.desk,.tools{width:min(100%,900px)}.head{display:flex;align-items:center;justify-content:space-between;gap:6px}.brand small{display:block;color:#a7f3d0;font-size:10px;font-weight:900;letter-spacing:.16em;text-transform:uppercase}.brand h1{margin:2px 0 0;font-size:clamp(21px,5vw,30px);letter-spacing:-.04em}.head-actions{display:flex;gap:4px}.head button,.tools button,.mode-card button,.result button{min-height:40px;border:1px solid var(--line);border-radius:11px;background:rgba(6,78,59,.86);color:#ecfdf5;font-weight:850;cursor:pointer}.head button{min-width:40px;padding:0 9px}
    .hud{display:grid;grid-template-columns:repeat(5,1fr);gap:4px}.stat{padding:5px 2px;border:1px solid rgba(255,255,255,.13);border-radius:9px;background:rgba(3,47,40,.58);text-align:center}.stat span{display:block;font-size:8px;color:#a7f3d0;font-weight:900;text-transform:uppercase;letter-spacing:.06em}.stat strong{display:block;margin-top:1px;font-size:clamp(12px,3.5vw,16px);font-variant-numeric:tabular-nums;white-space:nowrap}
    .desk{position:relative;flex:1;min-height:0;padding:7px;border:1px solid rgba(255,255,255,.12);border-radius:17px;background:rgba(3,76,60,.40);box-shadow:0 20px 55px rgba(0,0,0,.28);overflow:auto}.top-row{display:flex;justify-content:space-between;align-items:start;gap:8px}.stock-group,.foundations{display:flex;gap:clamp(3px,1vw,8px)}.pile,.foundation{position:relative;width:clamp(39px,11.2vw,76px);aspect-ratio:.70;border-radius:7px;border:2px dashed rgba(236,253,245,.22);display:flex;align-items:center;justify-content:center;color:rgba(236,253,245,.38);font-size:clamp(20px,7vw,38px);touch-action:manipulation}.pile.stock.has-card{border-style:solid;background:repeating-linear-gradient(45deg,#1d4ed8 0 6px,#1e40af 6px 12px);box-shadow:inset 0 0 0 3px #dbeafe}.pile.stock.has-card::after{content:"N";font-weight:1000;color:#fff;font-size:18px;text-shadow:0 2px 4px #000}.foundation[data-suit="♥"],.foundation[data-suit="♦"]{color:rgba(254,202,202,.48)}
    .tableau{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:clamp(2px,.8vw,7px);margin-top:10px;min-height:390px}.column{position:relative;min-width:0;min-height:360px;border-radius:8px}.card{position:absolute;left:0;width:100%;aspect-ratio:.70;border-radius:clamp(5px,1.2vw,9px);border:1px solid rgba(15,23,42,.28);background:#f8fafc;color:#0f172a;box-shadow:0 3px 7px rgba(0,0,0,.25);padding:clamp(2px,.7vw,6px);font-weight:900;touch-action:manipulation;cursor:pointer;transition:transform .12s,outline .12s}.card.red{color:#dc2626}.card.back{background:repeating-linear-gradient(45deg,#1d4ed8 0 5px,#1e3a8a 5px 10px);box-shadow:inset 0 0 0 3px #dbeafe,0 3px 7px rgba(0,0,0,.25);color:transparent}.card.selected{outline:3px solid #fde047;outline-offset:-2px;transform:translateY(-3px);z-index:50!important}.card.hint{animation:pulse .7s ease-in-out 2}.corner{display:flex;flex-direction:column;align-items:center;width:max-content;font-size:clamp(9px,2.9vw,18px);line-height:.9}.big-suit{position:absolute;inset:26% 0 auto;text-align:center;font-size:clamp(17px,6vw,38px)}.waste-card,.foundation-card{inset:0}.empty-king{font-size:clamp(17px,5vw,28px);opacity:.35}.tools{display:grid;grid-template-columns:repeat(5,1fr);gap:4px}.tools button{padding:6px 2px;font-size:10px}.tools .primary{background:rgba(14,116,144,.36);border-color:rgba(103,232,249,.45)}.tools button:disabled{opacity:.4}
    .overlay{position:fixed;inset:0;z-index:80;display:flex;align-items:center;justify-content:center;padding:18px;background:rgba(2,6,23,.84);backdrop-filter:blur(12px)}.overlay.hidden{display:none}.mode-card,.result{width:min(100%,440px);border:1px solid rgba(52,211,153,.28);border-radius:20px;background:linear-gradient(155deg,#064e3b,#0f172a);padding:22px;box-shadow:0 30px 80px rgba(0,0,0,.6)}.mode-card small,.result small{color:#a7f3d0;font-weight:900;letter-spacing:.15em;text-transform:uppercase}.mode-card h2,.result h2{margin:5px 0 8px;font-size:27px;letter-spacing:-.04em}.mode-card p,.result p{color:#d1fae5;line-height:1.5}.mode-list{display:grid;gap:7px}.mode-list button{padding:11px;text-align:left}.mode-list strong,.mode-list span{display:block}.mode-list span{font-size:11px;color:#a7f3d0;margin-top:2px}.mode-list .recommended{border-color:#6ee7b7;background:rgba(16,185,129,.14)}.actions{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:14px}.result button{padding:11px}.result .primary{background:#047857;border-color:#34d399}.toast{position:fixed;left:50%;bottom:max(12px,env(safe-area-inset-bottom));transform:translateX(-50%) translateY(15px);opacity:0;z-index:110;background:#0f172a;border:1px solid rgba(255,255,255,.18);border-radius:999px;padding:8px 12px;font-size:11px;font-weight:900;transition:.18s;pointer-events:none}.toast.show{opacity:1;transform:translateX(-50%) translateY(0)}@keyframes pulse{50%{filter:brightness(1.35);transform:translateY(-5px);outline:3px solid #fde047}}
    @media(max-width:430px){.desk{padding:5px}.tableau{margin-top:7px;min-height:330px}.column{min-height:320px}.tools button{font-size:9px;min-height:38px}}
  `;doc.head.appendChild(style);
  doc.body.innerHTML=`
    <main class="sol-app"><header class="head"><div class="brand"><small>Arcade NOWIS</small><h1>Solitaire</h1></div><div class="head-actions"><button id="soundBtn">🔊</button><button id="statsBtn">🏆</button></div></header>
    <section class="hud"><div class="stat"><span>Score</span><strong id="score">0</strong></div><div class="stat"><span>Temps</span><strong id="time">0:00</strong></div><div class="stat"><span>Coups</span><strong id="moves">0</strong></div><div class="stat"><span>Pioche</span><strong id="draw">1</strong></div><div class="stat"><span>Fondations</span><strong id="progress">0/52</strong></div></section>
    <section class="desk"><div class="top-row"><div class="stock-group"><div class="pile stock" id="stock"></div><div class="pile" id="waste"></div></div><div class="foundations" id="foundations"></div></div><div class="tableau" id="tableau"></div></section>
    <section class="tools"><button class="primary" id="hintBtn">💡 Indice</button><button id="undoBtn">↶ Annuler</button><button id="autoBtn">✨ Auto</button><button id="newBtn">↻ Nouvelle</button><button id="modeBtn">⚙ Mode</button></section></main>
    <div class="overlay" id="modeOverlay"><section class="mode-card"><small>Solitaire NOWIS</small><h2>Choisis ton défi</h2><p>Version Klondike tactile avec annulation fiable, double-tap vers les fondations, indice et auto-finition.</p><div class="mode-list"><button class="recommended" data-mode="detente"><strong>☕ Détente</strong><span>Pioche 1 · recyclage illimité · annulations illimitées</span></button><button data-mode="classique"><strong>♣ Classique</strong><span>Pioche 1 · 3 recyclages · score standard</span></button><button data-mode="expert"><strong>🔥 Expert</strong><span>Pioche 3 · 1 recyclage · aucun indice automatique</span></button></div></section></div>
    <div class="overlay hidden" id="resultOverlay"><section class="result"><small>Victoire</small><h2>Solitaire réussi !</h2><p id="resultText"></p><div class="actions"><button class="primary" id="againBtn">Rejouer</button><button id="resultMode">Changer de mode</button></div></section></div>
    <div class="overlay hidden" id="statsOverlay"><section class="result"><small>Statistiques</small><h2>Tes parties</h2><p id="statsText"></p><div class="actions"><button class="primary" id="closeStats">Fermer</button><button id="resetStats">Réinitialiser</button></div></section></div>
    <div class="toast" id="toast"></div>
  `;
  const tableauEl=doc.getElementById('tableau')!,stockEl=doc.getElementById('stock')!,wasteEl=doc.getElementById('waste')!,foundationsEl=doc.getElementById('foundations')!,scoreEl=doc.getElementById('score')!,timeEl=doc.getElementById('time')!,movesEl=doc.getElementById('moves')!,drawEl=doc.getElementById('draw')!,progressEl=doc.getElementById('progress')!,undoBtn=doc.getElementById('undoBtn') as HTMLButtonElement,hintBtn=doc.getElementById('hintBtn') as HTMLButtonElement,autoBtn=doc.getElementById('autoBtn') as HTMLButtonElement,modeOverlay=doc.getElementById('modeOverlay')!,resultOverlay=doc.getElementById('resultOverlay')!,resultText=doc.getElementById('resultText')!,statsOverlay=doc.getElementById('statsOverlay')!,statsText=doc.getElementById('statsText')!,toastEl=doc.getElementById('toast')!,soundBtn=doc.getElementById('soundBtn') as HTMLButtonElement;
  let state=deal(),difficulty:Difficulty='detente',history:Snapshot[]=[],selected:{source:Source;cards:Card[]}|null=null,elapsed=0,timer:number|null=null,running=false,soundOn=true,lastTap:{id:string;at:number}|null=null;
  type AudioWin=Window&typeof globalThis&{webkitAudioContext?:typeof AudioContext};const AC=(win as AudioWin).AudioContext||(win as AudioWin).webkitAudioContext;let audio:AudioContext|null=null;function tone(f:number,d=.045){if(!soundOn||!AC)return;try{audio??=new AC();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
  function toast(t:string){toastEl.textContent=t;toastEl.classList.add('show');win.setTimeout(()=>toastEl.classList.remove('show'),1100)}
  function save(){history.push({state:cloneState(state),elapsed});if(history.length>120)history.shift()}
  function config(){return difficulty==='detente'?{draw:1,recycles:999,hints:true}:difficulty==='classique'?{draw:1,recycles:3,hints:true}:{draw:3,recycles:1,hints:false}}
  function faceUpTop(col:Card[]){return col.length?col[col.length-1]:null}
  function sourceCards(source:Source):Card[]{if(source.type==='waste'){const c=state.waste.at(-1);return c?[c]:[]}if(source.type==='foundation'){const c=state.foundations[source.suit].at(-1);return c?[c]:[]}return state.tableau[source.col].slice(source.index)}
  function removeSource(source:Source,count:number){if(source.type==='waste')state.waste.pop();else if(source.type==='foundation')state.foundations[source.suit].pop();else state.tableau[source.col].splice(source.index,count)}
  function revealAfter(source:Source){if(source.type!=='tableau')return;const top=faceUpTop(state.tableau[source.col]);if(top&&!top.faceUp){top.faceUp=true;state.score+=5}}
  function perform(source:Source,cards:Card[],dest:Destination):boolean{if(!cards.length||!movableSequence(cards))return false;if(dest.type==='foundation'){if(cards.length!==1||!canFoundation(cards[0],state.foundations[dest.suit])||cards[0].suit!==dest.suit)return false}else if(!canTableau(cards[0],state.tableau[dest.col]))return false;save();removeSource(source,cards.length);if(dest.type==='foundation'){state.foundations[dest.suit].push(cards[0]);state.score+=source.type==='tableau'?10:source.type==='waste'?10:-15}else{state.tableau[dest.col].push(...cards);state.score+=source.type==='waste'?5:source.type==='foundation'?-15:0}revealAfter(source);state.moves++;selected=null;tone(cards[0].rank===1?680:430);render();checkWin();return true}
  function autoFoundation(source:Source,card:Card){if(canFoundation(card,state.foundations[card.suit]))return perform(source,[card],{type:'foundation',suit:card.suit});return false}
  function drawStock(){if(!running)return;const cfg=config();if(state.stock.length===0){if(!state.waste.length)return;if(state.recycles>=cfg.recycles){toast('Plus de recyclage de pioche');return}save();state.stock=state.waste.reverse().map(c=>({...c,faceUp:false}));state.waste=[];state.recycles++;state.moves++;state.score=Math.max(0,state.score-20);tone(250);render();return}save();for(let i=0;i<cfg.draw&&state.stock.length;i++){const c=state.stock.pop()!;c.faceUp=true;state.waste.push(c)}state.moves++;tone(320);render()}
  function cardMarkup(card:Card,classes='',top=0,z=1){return`<button type="button" class="card ${isRed(card.suit)?'red':''} ${card.faceUp?'':'back'} ${classes}" data-card="${card.id}" style="top:${top}px;z-index:${z}">${card.faceUp?`<span class="corner"><span>${rankLabel(card.rank)}</span><span>${card.suit}</span></span><span class="big-suit">${card.suit}</span>`:''}</button>`}
  function render(){stockEl.className=`pile stock ${state.stock.length?'has-card':''}`;stockEl.innerHTML='';const waste=state.waste.at(-1);wasteEl.innerHTML=waste?cardMarkup(waste,selected?.cards[0]?.id===waste.id?'selected':''):'';foundationsEl.innerHTML='';for(const suit of SUITS){const slot=doc.createElement('div');slot.className='foundation';slot.dataset.suit=suit;const card=state.foundations[suit].at(-1);slot.innerHTML=card?cardMarkup(card,selected?.cards[0]?.id===card.id?'selected':''):`<span>${suit}</span>`;foundationsEl.appendChild(slot)}tableauEl.innerHTML='';state.tableau.forEach((col,colIndex)=>{const colEl=doc.createElement('div');colEl.className='column';colEl.dataset.col=String(colIndex);let y=0;col.forEach((card,index)=>{const selectedClass=selected?.cards.some(c=>c.id===card.id)?'selected':'';colEl.insertAdjacentHTML('beforeend',cardMarkup(card,selectedClass,y,index+1));y+=card.faceUp?Math.min(30,Math.max(18,250/(col.length||1))):Math.min(18,Math.max(10,130/(col.length||1)))});if(!col.length)colEl.innerHTML='<span class="empty-king">K</span>';tableauEl.appendChild(colEl)});scoreEl.textContent=String(state.score);movesEl.textContent=String(state.moves);drawEl.textContent=String(config().draw);progressEl.textContent=`${SUITS.reduce((n,s)=>n+state.foundations[s].length,0)}/52`;undoBtn.disabled=!history.length;hintBtn.disabled=!config().hints;autoBtn.disabled=false}
  function locateCard(id:string):Source|null{const waste=state.waste.at(-1);if(waste?.id===id)return{type:'waste'};for(const suit of SUITS)if(state.foundations[suit].at(-1)?.id===id)return{type:'foundation',suit};for(let col=0;col<7;col++){const index=state.tableau[col].findIndex(c=>c.id===id);if(index>=0)return{type:'tableau',col,index}}return null}
  function selectCard(id:string){const source=locateCard(id);if(!source)return;const cards=sourceCards(source);if(!cards.length||!cards[0].faceUp||!movableSequence(cards))return;const now=Date.now();if(lastTap?.id===id&&now-lastTap.at<420&&cards.length===1){lastTap=null;if(autoFoundation(source,cards[0]))return}lastTap={id,at:now};if(selected&&selected.cards[0].id===id){selected=null;render();return}selected={source,cards};tone(280,.025);render()}
  doc.addEventListener('click',(e)=>{const target=e.target as Element|null;const card=target?.closest<HTMLElement>('[data-card]');if(card){selectCard(card.dataset.card!);return}const foundation=target?.closest<HTMLElement>('.foundation');if(foundation&&selected){perform(selected.source,selected.cards,{type:'foundation',suit:foundation.dataset.suit as Suit});return}const column=target?.closest<HTMLElement>('.column');if(column&&selected)perform(selected.source,selected.cards,{type:'tableau',col:Number(column.dataset.col)})});stockEl.addEventListener('click',drawStock);
  function undo(){const snap=history.pop();if(!snap)return;state=cloneState(snap.state);elapsed=snap.elapsed;selected=null;tone(220);render()}
  function findHint(){const waste=state.waste.at(-1);if(waste){if(canFoundation(waste,state.foundations[waste.suit]))return{source:{type:'waste'}as Source,card:waste,text:'Place cette carte sur sa fondation'};for(let col=0;col<7;col++)if(canTableau(waste,state.tableau[col]))return{source:{type:'waste'}as Source,card:waste,text:`Déplace la pioche vers la colonne ${col+1}`}}for(let col=0;col<7;col++){const cards=state.tableau[col];for(let i=0;i<cards.length;i++){const card=cards[i];if(!card.faceUp)continue;if(i===cards.length-1&&canFoundation(card,state.foundations[card.suit]))return{source:{type:'tableau',col,index:i}as Source,card,text:'Monte cette carte sur sa fondation'};const seq=cards.slice(i);if(!movableSequence(seq))continue;for(let to=0;to<7;to++)if(to!==col&&canTableau(card,state.tableau[to]))return{source:{type:'tableau',col,index:i}as Source,card,text:`Déplace cette suite vers la colonne ${to+1}`}}}return null}
  function hint(){if(!config().hints){toast('Indices désactivés en mode Expert');return}const h=findHint();if(!h){toast(state.stock.length?'Essaie la prochaine carte de la pioche':'Aucun coup évident');return}selected={source:h.source,cards:sourceCards(h.source)};render();const node=doc.querySelector<HTMLElement>(`[data-card="${h.card.id}"]`);node?.classList.add('hint');win.setTimeout(()=>node?.classList.remove('hint'),1300);toast(h.text);tone(650,.06)}
  function safeAutoMove():boolean{const candidates:{source:Source;card:Card}[]=[];const waste=state.waste.at(-1);if(waste)candidates.push({source:{type:'waste'},card:waste});for(let col=0;col<7;col++){const card=state.tableau[col].at(-1);if(card?.faceUp)candidates.push({source:{type:'tableau',col,index:state.tableau[col].length-1},card})}for(const {source,card} of candidates){if(canFoundation(card,state.foundations[card.suit])){const oppositeColors=SUITS.filter(s=>isRed(s)!==isRed(card.suit));const safe=card.rank<=2||oppositeColors.every(s=>(state.foundations[s].at(-1)?.rank||0)>=card.rank-1);if(safe)return perform(source,[card],{type:'foundation',suit:card.suit})}}return false}
  function autoFinish(){let count=0;const step=()=>{if(!running)return;if(safeAutoMove()){count++;win.setTimeout(step,130)}else{if(count)toast(`${count} carte${count>1?'s':''} montée${count>1?'s':''}`);else toast('Aucune carte sûre à monter')}};step()}
  function checkWin(){const total=SUITS.reduce((n,s)=>n+state.foundations[s].length,0);if(total!==52)return;running=false;if(timer!==null){win.clearInterval(timer);timer=null}const raw=win.localStorage.getItem(BEST_KEY);let stats:{wins:number;games:number;bestTime:number|null}=raw?JSON.parse(raw):{wins:0,games:0,bestTime:null};stats.wins++;stats.bestTime=stats.bestTime===null?elapsed:Math.min(stats.bestTime,elapsed);win.localStorage.setItem(BEST_KEY,JSON.stringify(stats));resultText.textContent=`Temps : ${formatTime(elapsed)} · Coups : ${state.moves} · Score : ${state.score}`;resultOverlay.classList.remove('hidden');tone(820,.12);win.setTimeout(()=>tone(1050,.14),100)}
  function formatTime(s:number){return`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
  function start(mode:Difficulty){difficulty=mode;state=deal();history=[];selected=null;elapsed=0;running=true;modeOverlay.classList.add('hidden');resultOverlay.classList.add('hidden');if(timer!==null)win.clearInterval(timer);timer=win.setInterval(()=>{if(running){elapsed++;timeEl.textContent=formatTime(elapsed)}},1000);timeEl.textContent='0:00';render();tone(520,.07)}
  function newGame(){const raw=win.localStorage.getItem(BEST_KEY);let stats:{wins:number;games:number;bestTime:number|null}=raw?JSON.parse(raw):{wins:0,games:0,bestTime:null};stats.games++;win.localStorage.setItem(BEST_KEY,JSON.stringify(stats));start(difficulty)}
  doc.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(btn=>btn.addEventListener('click',()=>start(btn.dataset.mode as Difficulty)));doc.getElementById('undoBtn')?.addEventListener('click',undo);doc.getElementById('hintBtn')?.addEventListener('click',hint);doc.getElementById('autoBtn')?.addEventListener('click',autoFinish);doc.getElementById('newBtn')?.addEventListener('click',newGame);doc.getElementById('modeBtn')?.addEventListener('click',()=>modeOverlay.classList.remove('hidden'));doc.getElementById('againBtn')?.addEventListener('click',newGame);doc.getElementById('resultMode')?.addEventListener('click',()=>{resultOverlay.classList.add('hidden');modeOverlay.classList.remove('hidden')});
  doc.getElementById('statsBtn')?.addEventListener('click',()=>{const raw=win.localStorage.getItem(BEST_KEY);const stats:{wins:number;games:number;bestTime:number|null}=raw?JSON.parse(raw):{wins:0,games:0,bestTime:null};statsText.textContent=`Parties lancées : ${stats.games} · Victoires : ${stats.wins} · Meilleur temps : ${stats.bestTime===null?'—':formatTime(stats.bestTime)}`;statsOverlay.classList.remove('hidden')});doc.getElementById('closeStats')?.addEventListener('click',()=>statsOverlay.classList.add('hidden'));doc.getElementById('resetStats')?.addEventListener('click',()=>{win.localStorage.removeItem(BEST_KEY);statsText.textContent='Statistiques réinitialisées.'});soundBtn.addEventListener('click',()=>{soundOn=!soundOn;soundBtn.textContent=soundOn?'🔊':'🔇';if(soundOn)tone(520,.06)});
  render();
}
