import Image from 'next/image';
import Link from 'next/link';
import { buildMetadata } from '@/lib/seo';
import { CreationFlow, GuideHelp, RevidOffer } from '@/components/marketing/GuideElements';
import { CopyPrompt } from '@/components/marketing/CopyPrompt';
import { songWritingPrompt, musicStylePrompt, videoDirectionPrompt } from '@/data/creationGuide';
export const metadata = buildMetadata({title:'Guide pratique ChatGPT, Suno et Revid pour créer une chanson',description:'Apprenez à préparer vos paroles, choisir un style musical, télécharger votre MP3 et créer une vidéo. Exemples de prompts, images et repères pour débuter.',path:'/outils-creation-musicale'});

export default function MusicToolsGuidePage() {
  return <article className="nm-page ng-guide"><header className="nm-section"><p className="nm-eyebrow">Le guide pratique · Débuter à son rythme</p><h1 className="nm-page-title">Trois outils.<br /><em>Votre propre histoire.</em></h1><p className="nm-intro">Comprendre le rôle de chaque application, préparer ce qu’on lui donne et améliorer ce qu’elle propose.</p><p className="nm-fine">Repères vérifiés le 28 septembre 2026. Les menus et les fonctions peuvent varier selon l’appareil et le forfait.</p><nav className="nm-actions" aria-label="Sommaire du guide"><a className="cta-secondary" href="#chatgpt">1. ChatGPT</a><a className="cta-secondary" href="#suno">2. Suno</a><a className="cta-secondary" href="#revid">3. Revid</a></nav></header><CreationFlow />
    <div className="ng-reading">
      <section id="chatgpt"><p className="nm-eyebrow">01 · L’atelier des paroles</p><h2>ChatGPT : mettre votre histoire en mots.</h2><p>ChatGPT est un assistant de conversation. Ici, il aide à trouver des formulations, organiser les couplets et explorer des rimes. Vous lui donnez la matière personnelle et vous choisissez ce qui mérite de rester.</p><ol><li><strong>Ouvrez une conversation sur <a href="https://chatgpt.com" target="_blank" rel="noopener noreferrer">ChatGPT ↗</a>.</strong> Préparez vos souvenirs et votre intention dans un document.</li><li><strong>Écrivez votre consigne dans la zone de message.</strong> Remplacez les passages entre crochets du modèle ci-dessous. Écartez les détails privés inutiles.</li><li><strong>Envoyez le message et répondez aux questions.</strong> Demandez ensuite une première structure : couplets, refrain, pont.</li><li><strong>Travaillez par passages.</strong> Précisez les lignes à garder et l’émotion à renforcer. Demandez plusieurs variantes d’un refrain au lieu de tout recommencer.</li><li><strong>Relisez et copiez le texte final.</strong> Retirez les commentaires de l’assistant : seules les paroles doivent partir dans Suno.</li></ol><CopyPrompt title="Votre première consigne" text={songWritingPrompt} /><div className="ng-note"><strong>Exemple de progression</strong><p>« Je veux une chanson touchante » → « Je veux remercier mon père pour sa présence discrète » → « Garde le souvenir du trajet en voiture, raccourcis le refrain et remplace les grandes déclarations par des gestes concrets. »</p></div><p className="nm-fine">Repères : <a href="https://help.openai.com/en/articles/10032626-prompt-engineering-best-practices-for-chatgpt">conseils officiels pour formuler et améliorer une demande</a>. Les modèles de ce guide sont des exemples créés pour Nowis.</p></section>
      <section id="suno"><p className="nm-eyebrow">02 · L’atelier musical</p><h2>Suno : essayer une voix, un style, une énergie.</h2><p>Suno transforme une direction et des paroles en propositions musicales. Préparez deux éléments séparés : le texte à chanter et la description du son que vous imaginez.</p><ol><li>Ouvrez <a href="https://suno.com/create" target="_blank" rel="noopener noreferrer">Create dans Suno ↗</a>, puis choisissez <strong>Custom</strong>.</li><li>Collez vos paroles dans le champ prévu. Vérifiez les retours à la ligne et les prénoms.</li><li>Dans <strong>Styles</strong>, décrivez le genre, les instruments, la voix et l’ambiance. Donnez un titre à la version.</li><li>Lancez la création, puis écoutez. Comparez la prononciation, le rythme et l’émotion. Modifiez un élément à la fois pour comprendre son effet.</li><li>Dans les options de la chanson retenue, cherchez le téléchargement et choisissez <strong>MP3</strong>. Les formats supplémentaires dépendent du forfait et de l’appareil.</li></ol><CopyPrompt title="Exemple de direction musicale" text={musicStylePrompt} /><figure><Image src="/images/guides/suno-playlists.jpg" width={1200} height={675} alt="Présentation officielle des playlists Suno pour retrouver et organiser ses chansons" sizes="(max-width: 900px) 90vw, 800px" /><figcaption>Visuel officiel de l’organisation en playlists dans Suno. Utilisez des titres distincts pour retrouver vos essais. <a href="https://blog.suno.com/release-notes">Source : Suno, notes de version</a>.</figcaption></figure><details className="ng-details"><summary>Pour aller plus loin : à quoi ressemble Suno Studio ?</summary><figure><Image src="/images/guides/suno.jpg" width={1200} height={675} alt="Capture officielle de Suno Studio montrant plusieurs pistes audio et des réglages d’instrument" sizes="(max-width: 900px) 90vw, 800px" /><figcaption>Capture officielle de Suno Studio, un espace de travail avancé. Ce n’est pas l’écran Custom décrit ci-dessus et il n’est pas nécessaire pour suivre la méthode de base. <a href="https://blog.suno.com/release-notes">Source : Suno</a>.</figcaption></figure></details><p className="nm-fine">Aide officielle : <a href="https://help.suno.com/en/articles/2415873">utiliser ses propres paroles</a> · <a href="https://help.suno.com/en/articles/13926081">options de téléchargement</a>.</p></section>
      <section id="revid"><p className="nm-eyebrow">03 · L’atelier vidéo</p><h2>Revid : accompagner la chanson avec des images.</h2><p>Vous partez ici du MP3 final téléchargé depuis Suno. Je trouve Revid dispendieux : vérifiez le coût estimé avant de lancer la génération et commencez par un extrait.</p><ol><li>Ouvrez l’outil <a href="https://www.revid.ai/tools/ai-music-video-generator" target="_blank" rel="noopener noreferrer">AI Music Video Generator ↗</a> et importez votre MP3.</li><li>Choisissez le format : <strong>9:16 vertical</strong> pour Shorts et Reels, ou <strong>16:9 horizontal</strong> pour une vidéo YouTube classique.</li><li>Décrivez l’univers visuel. Choisissez le type d’images et le rythme selon les options proposées.</li><li>Générez un court essai, regardez-le, puis ajustez votre direction avant la version complète.</li><li>Dans l’éditeur, revoyez les scènes, le montage et les sous-titres. Corrigez les noms et vérifiez la fin avant l’export.</li></ol><div className="ng-ratios" role="img" aria-label="Comparaison des formats : 9 sur 16 vertical pour Shorts et Reels, 16 sur 9 horizontal pour une vidéo YouTube"><div><span className="ng-vertical">9:16</span><p>Shorts · Reels</p></div><div><span className="ng-horizontal">16:9</span><p>YouTube · format paysage</p></div></div><p className="nm-fine">Schéma pédagogique Nowis des formats vidéo.</p><CopyPrompt title="Exemple de direction visuelle" text={videoDirectionPrompt} /><p className="nm-fine">Source : <a href="https://www.revid.ai/tools/ai-music-video-generator">guide officiel du générateur de clips Revid</a>.</p><RevidOffer /></section>
      <section><h2>Un problème ? Commencez par ce réglage.</h2><div className="ng-troubles"><details><summary>Les paroles sont trop génériques.</summary><p>Ajoutez un souvenir précis et demandez de remplacer une image vague par un geste ou un lieu réel. Gardez les phrases qui vous ressemblent déjà.</p></details><details><summary>La chanson chante mal mes phrases.</summary><p>Raccourcissez les lignes trop longues, simplifiez les mots difficiles et réessayez. Écoutez particulièrement les prénoms et le refrain.</p></details><details><summary>La vidéo ne raconte pas la bonne histoire.</summary><p>Précisez un sujet, un lieu et une ambiance cohérente. Revoyez les scènes qui contredisent les paroles avant de relancer une génération coûteuse.</p></details><details><summary>Je veux publier ou vendre le résultat.</summary><p>Consultez les conditions actuelles de chaque outil et de votre forfait avant un usage commercial. Conservez vos fichiers et vérifiez les autorisations pour les photos ou souvenirs personnels diffusés.</p></details></div><p><Link className="nm-text-link" href="/comment-je-cree">Lire la méthode personnelle de Nowis ↗</Link></p></section>
    </div><GuideHelp />
  </article>;
}
