import Link from 'next/link';
import { buildMetadata } from '@/lib/seo';
import { CreationFlow, GuideHelp, RevidOffer } from '@/components/marketing/GuideElements';
import { CopyPrompt } from '@/components/marketing/CopyPrompt';
import { songWritingPrompt, revisionPrompt } from '@/data/creationGuide';
export const metadata = buildMetadata({title:'Comment je crée mes chansons avec ChatGPT, Suno et Revid',description:'La méthode de Nowis : raconter une histoire, retravailler les paroles avec ChatGPT, créer la musique dans Suno et réaliser une vidéo avec Revid.',path:'/comment-je-cree'});

export default function CreationMethodPage() {
  return <article className="nm-page ng-guide">
    <header className="nm-section"><p className="nm-eyebrow">Dans les coulisses · La méthode de Nowis</p><h1 className="nm-page-title">Avant la musique,<br /><em>il y a une émotion.</em></h1><p className="nm-intro">J’utilise ChatGPT pour travailler les textes et les rimes, Suno pour créer la musique, puis Revid pour la vidéo. Mais tout commence avec une histoire que j’ai envie de raconter.</p><div className="nm-actions"><a href="#paroles" className="cta-primary">Découvrir ma méthode ↓</a><Link href="/outils-creation-musicale" className="cta-secondary">Le guide des applications</Link></div></header>
    <CreationFlow />
    <div className="ng-reading">
      <section id="paroles"><p className="nm-eyebrow">01 · Donner une intention au texte</p><h2>Je raconte beaucoup avant de demander une chanson.</h2><p>Mon prompt, c’est la consigne que je donne à ChatGPT. Je prends le temps d’expliquer la personne, l’histoire, les souvenirs et surtout les émotions que je recherche. Un long prompt peut être utile quand il contient des détails qui comptent.</p><p>Plutôt que « écris une chanson d’amour », je décris ce qui rend cette relation unique : les petites habitudes, les moments traversés, ce que je n’ai jamais réussi à dire. Je précise aussi le ton, les mots à éviter et l’émotion que je veux laisser à la fin.</p><CopyPrompt title="Un point de départ à personnaliser" text={songWritingPrompt} /></section>
      <section><p className="nm-eyebrow">02 · Réécrire fait partie de la création</p><h2>Ne vous arrêtez pas à la première version.</h2><p>Il ne faut pas avoir peur de remodifier jusqu’à retrouver la chanson qu’on recherche. Je peux aimer une ligne, garder un refrain et refaire tout un couplet. Les rimes doivent servir le sens, pas prendre sa place.</p><p>Lisez les paroles à voix haute. Une phrase vous ressemble-t-elle vraiment ? Un souvenir est-il exact ? Y a-t-il trop de mots pour chanter naturellement ? Dites précisément à ChatGPT ce qui fonctionne et ce qui doit changer.</p><CopyPrompt title="Un exemple de demande de réécriture" text={revisionPrompt} /><p className="ng-note">Astuce : gardez vos versions dans un document. Vous pourrez retrouver une belle phrase même si la version suivante vous plaît moins.</p></section>
      <section><p className="nm-eyebrow">03 · Passer des paroles à la musique</p><h2>Dans Suno, je choisis une direction musicale.</h2><p>Quand le texte me convient, je le copie dans le mode Custom de Suno. Je choisis le style voulu : genre, instruments, énergie, ambiance et façon de chanter. Je crée des propositions, puis j’écoute si la musique porte vraiment les mots.</p><p>Si le résultat ne transmet pas l’émotion recherchée, je retravaille le style ou les paroles. Une fois la bonne version choisie, je télécharge le fichier MP3 et je le conserve avec mon texte final.</p><Link className="nm-text-link" href="/outils-creation-musicale#suno">Suivre les étapes dans Suno ↗</Link></section>
      <section><p className="nm-eyebrow">04 · Donner des images à la chanson</p><h2>La vidéo vient après le choix de la chanson.</h2><p>J’importe le MP3 téléchargé depuis Suno dans Revid, puis je prépare l’univers visuel. Les images doivent accompagner l’histoire et son émotion. Je regarde le résultat, je corrige les scènes et les textes qui ne conviennent pas, puis j’exporte la vidéo.</p><p>Je trouve Revid dispendieux. Pour commencer, mieux vaut préparer sa direction et tester un court extrait avant de générer une chanson complète. La vidéo reste facultative : votre chanson peut déjà se partager en audio.</p><Link className="nm-text-link" href="/outils-creation-musicale#revid">Suivre les étapes dans Revid ↗</Link><RevidOffer /></section>
      <section><h2>Mon dernier passage avant de partager</h2><ul><li>Les paroles racontent-elles ce que je voulais dire ?</li><li>Les noms et les mots importants sont-ils bien prononcés ?</li><li>La musique, les images et les sous-titres vont-ils ensemble ?</li><li>Ai-je conservé le texte final, le MP3 et la vidéo ?</li></ul><p>Pour publier ou vendre une création, consultez les conditions des outils et de votre forfait. Demandez aussi l’accord des personnes avant de diffuser leurs photos ou une histoire privée.</p></section>
    </div><GuideHelp />
  </article>;
}
